#Requires -Version 5.1
<#
.SYNOPSIS
    Shared helpers for cocopilot's launcher scripts. Dot-source this, don't
    run it directly.
#>

function ConvertTo-SingleQuoted {
    param([string]$Value)
    return "'" + ($Value -replace "'", "''") + "'"
}

function Write-MailboxJson {
    <#
    .SYNOPSIS
        Replaces a mailbox JSON file (implementer.json) whole-file via
        same-directory temp-file rename: best-effort crash safety against
        torn/partial writes. Deliberately NOT atomic in any API-contract
        sense, and no protection against two valid concurrent writers —
        last writer wins; the epoch rule and the user resolve those races
        (see COLLABORATION.md).
    #>
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)]$Object
    )

    if (Test-Path -LiteralPath $Path -PathType Container) {
        throw "Write-MailboxJson: -Path must be a file, but a directory exists there: $Path"
    }

    $dir = Split-Path -Parent $Path
    $tmp = Join-Path $dir (".{0}.{1}.tmp" -f (Split-Path -Leaf $Path), [Guid]::NewGuid().ToString("N"))
    # -Compress: non-compressed ConvertTo-Json output is formatted
    # differently by Windows PowerShell 5.1 vs pwsh 7, which would make this
    # watched file's bytes churn whenever the peer runs the other host.
    # Compressed output is byte-identical on both.
    $json = ($Object | ConvertTo-Json -Depth 5 -Compress) + "`n"
    $moved = $false
    try {
        # UTF-8 without BOM via .NET so Windows PowerShell 5.1 and pwsh 7
        # produce identical bytes.
        [System.IO.File]::WriteAllText($tmp, $json, [System.Text.UTF8Encoding]::new($false))
        # -ErrorAction Stop: the failure must terminate regardless of the
        # caller's $ErrorActionPreference, or the finally-cleanup is skipped
        # and a stale temp file leaks.
        Move-Item -LiteralPath $tmp -Destination $Path -Force -ErrorAction Stop
        $moved = $true
    } finally {
        if (-not $moved -and (Test-Path -LiteralPath $tmp)) {
            Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
        }
    }
}

function Get-CocopilotSessionBanner {
    <#
    .SYNOPSIS
        Builds the "session context" banner prepended to each agent's
        prompt, so the same static prompts/agent-*.md files can target any
        repository without hardcoding its name or path.
    #>
    param(
        [Parameter(Mandatory)][string]$RepoPath,
        [Parameter(Mandatory)][string]$CocopilotRoot,
        [Parameter(Mandatory)][ValidateSet("agent-a", "agent-b", "verifier")][string]$AgentRole
    )

    $collaborationPath = Join-Path $CocopilotRoot "COLLABORATION.md"
    $watchScript = Join-Path $CocopilotRoot "scripts\watch-mailbox.ps1"
    $initScript = Join-Path $CocopilotRoot "scripts\init-mailbox.ps1"
    $commonScript = Join-Path $CocopilotRoot "scripts\_common.ps1"
    $implementerJson = Join-Path $RepoPath ".mailbox\implementer.json"
    $watchCmd = "& $(ConvertTo-SingleQuoted $watchScript) -RepoPath $(ConvertTo-SingleQuoted $RepoPath)"
    $initCmd = "& $(ConvertTo-SingleQuoted $initScript) -RepoPath $(ConvertTo-SingleQuoted $RepoPath)"
    $ownershipCmd = ". $(ConvertTo-SingleQuoted $commonScript); Write-MailboxJson -Path $(ConvertTo-SingleQuoted $implementerJson) -Object `$record"

    $core = @"
## Session context (auto-generated by cocopilot — do not hand-edit)

- Your role: $AgentRole
- Target repository: $RepoPath
- Mailbox: $RepoPath\.mailbox\ (implementer.json, mailbox.md, session.log.md)
- Collaboration protocol: $collaborationPath
"@

    if ($AgentRole -eq "verifier") {
        # Read-only role: deliberately gets NO watch/init/ownership
        # commands — a verifier must never be handed a ready-to-run
        # mutating command.
        return $core + @"

- You are a read-only fresh-eyes verifier; no watch/init/ownership
  commands are provided to this role on purpose.

---

"@
    }

    return $core + @"

- Watch command (run in the background whenever you're idle/waiting):
  $watchCmd
- Init command (only if the mailbox files above don't exist yet):
  $initCmd
- Ownership-record update (the ONLY allowed way to write implementer.json —
  build `$record as the complete new object first, then run; never edit the
  file in place):
  $ownershipCmd

---

"@
}
